# Generated by Django 3.0.8 on 2020-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200712_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='elimination_round',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
