# Generated by Django 3.0.8 on 2020-07-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_racer_elimination_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='average_time_in_race',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='best_time_in_race',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='pb',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racerround',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
