# Generated by Django 3.0.8 on 2020-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200712_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerround',
            name='position_in_round',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
