# Generated by Django 3.0.8 on 2020-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tournament_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='font',
            field=models.CharField(choices=[('MANDELA_.TTF', 'Mandela'), ('bradley_gratis.ttf', 'Bradley Gratis'), ('GF-TecmoSet1.TTF', 'Tecmo 1'), ('GF-TecmoSet2.TTF', 'Tecmo 2')], default='Mandela', max_length=100),
        ),
    ]
