# Generated by Django 3.0.8 on 2020-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_tournament_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='font',
            field=models.CharField(choices=[('Mandela', 'Mandela'), ('Bradley_Gratis', 'Bradley_Gratis'), ('Tecmo_1', 'Tecmo_1'), ('Tecmo_2', 'Tecmo_2')], default='Mandela', max_length=100),
        ),
    ]
