# Generated by Django 3.0.8 on 2020-11-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20201007_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='racer',
            name='discord_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
